# Generated by Django 5.0.6 on 2024-07-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_emp_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='id',
            new_name='eid',
        ),
    ]
