# Generated by Django 4.2.7 on 2024-07-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_testimonial_alter_emp_working'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial',
            new_name='desc',
        ),
    ]
