# Generated by Django 4.2.7 on 2024-08-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_rename_testimonial_testimonial_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='desc',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
