# Generated by Django 4.2.7 on 2024-08-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0006_alter_testimonial_desc_alter_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='picture',
            field=models.FileField(upload_to='testimonials/'),
        ),
    ]
