# Generated by Django 4.2.7 on 2024-08-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0007_alter_testimonial_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='picture',
            new_name='file',
        ),
    ]
